### ISSUE TITLE
FR: Add ability to add custom templating for k3s containerd config

### ISSUE THREAD

**Issue by samip5** [onedr0p/cluster-template#1171]
It would be great if I could add custom things for containerd, eg: https://github.com/kubevirt/containerized-data-importer/blob/f5d0b70b096abd856acff67eb4fc0cab0b474d89/doc/block_cri_ownership_config.md

**Comment by onedr0p** [comment]
This makes sense, and could easily be done here however I wonder if this should be a supported feature in the upstream Galaxy role instead. I do this in my home-ops repo to add support for spegel but it's not ideal because containerd needs to be restarted after it _just_ started.

https://github.com/onedr0p/home-ops/blob/12a6abca499357fc6a7707e60b0e6f1c25451165/ansible/main/playbooks/cluster-installation.yaml#L72-L86

https://github.com/PyratLabs/ansible-role-k3s

**Comment by samip5** [comment]
I did create a FR in the sensible role too. ;)

**Comment by onedr0p** [comment]
Keep in mind that `config.toml.tmpl` file can be very different depending on what args / config you feed to k3s which makes templating it out a royal pain in the ass.

**Comment by samip5** [comment]
> Keep in mind that generated `config.toml.tmpl` file can be very different depending on what args / config you feed to k3s which makes templating it out a royal pain in the ass.

But: `You can extend the K3s base template instead of copy-pasting the complete stock template out of the K3s source code. This is useful if you need to build on the existing configuration, and add a few extra lines at the end.` - https://docs.k3s.io/advanced?#configuring-containerd

**Comment by onedr0p** [comment]
So from what we discovered that `{{ template "base" . }}` var won't merge keys, it only appends config to the bottom of the `containerd.toml.tmpl`

**Comment by onedr0p** [comment]
Putting a hold on this until if/when this gets implemented https://github.com/k3s-io/k3s/issues/9246

**Comment by onedr0p** [comment]
Upstream k3s won't support merging containerd configs (makes sense on their end) so I am going to close this as well.
