### ISSUE TITLE
The devcontainer build is broken due to linux/arm64 issues

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/cluster-template#1484]
One short fix would be to remove arm64 support for the devcontainer.

**Comment by onedr0p** [comment]
I have pushed a change to only build for amd64 for the time being, this broke two weeks ago with no clear reason as to why.

**Comment by jmuchovej** [comment]
Could you elaborate on what broke? I did some substantial overhaul on the devcontainer – I'm running on an M1 and my devcontainer built/runs natively.
(e.g., I don't use `fish`, wanted something I could work out of so as to not have other tools relevant to my cluster installed on my laptop, etc.)

I can rip out some of the customizations I made and submit a PR if you're open to it – this container comes in around 1GB compressed, ~4.5GB uncompressed. (I switched to `mcr.microsoft.com/devcontainers/python:3.11-bookworm`, since Alpine isn't supported by some devcontainer features, like `docker-outside-of-docker`.)

**Comment by onedr0p** [comment]
The devcontainer GHA had issues building for arm64 it might be fixed now but I haven't had time to revisit it. I mainly stuck with alpine because it has more [CLI tools with recent versions](https://github.com/onedr0p/cluster-template/blob/main/.devcontainer/ci/features/install.sh#L5-L16), this allowed me to not have to hunt around for 3rd party devcontainer packages to include.

**Comment by onedr0p** [comment]
Fixed using the ubuntu-24.04 runner

https://github.com/onedr0p/cluster-template/commit/643e682982d4f7f138a7808a9ede6012ece5ab48
